apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260609-234617-nt5p8ts7cc68-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260609-234617-nt5p8ts7cc68.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260609-234617-nt5p8ts7cc68-service
            port:
              number: 80
