apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260609-234617-nt5p8ts7cc68-service
spec:
  selector:
    app: enterprise-system-20260609-234617-nt5p8ts7cc68
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
